### ISSUE TITLE
Integrate with `fpm`

### ISSUE THREAD

**Issue by certik** [fortran-lang/test-drive#4]
The `fpm` new should use some testing framework and set things up, so depend on `test-drive` and add a simple test. Then you can easily extend it as needed.

We should allow (in the future) to use any testing framework in `fpm`, configurable with a command line option. But we can use test-drive as the default.

**Comment by awvwgk** [comment]
We already have the functionality in fpm to use development (*i.e.* testing) dependencies with

```toml
[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
```

Which makes the dependencies available to all tests, but does not make it a transient dependency for dependent projects.

Alternatively we also can limit the scope to a single test target by using

```toml
[[test]]
name = "tester"
[test.dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
```

In `fpm new` we can setup the boilerplate code from the README of this project by default, which provides a fully working testing framework with support for multiple suites with different unit tests.
